### ISSUE TITLE
trying to go to definition crashes language_server-ruby

### ISSUE THREAD

**Issue by ibotty** [mtsmfm/language_server-ruby#29]
See the following log from [neovim's language server client](https://github.com/autozimu/LanguageClient-neovim).

```
D, [2017-10-12T12:43:06.091826 #4184] DEBUG -- : Receive: {
  "jsonrpc": "2.0",
  "id": 2,
  "method": "textDocument/definition",
  "params": {
    "textDocument": {
      "uri": "file:///home/tob/src/kulturweit/kulturweit-web/app/views/jobs/offers/index.html.haml"
    },
    "position": {
      "line": 13,
      "character": 43
    }
  }
}
/home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server/project.rb:15:in `find_definition
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server/definition_provider/
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:139:in `each'
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:139:in `flat_map'
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:139:in `block in 
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:45:in `block in r
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-protocol-0.4.0/lib/language_server/protocol/tr
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:34:in `run'
        from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/exe/language_server-ruby:8:in `<top (req
        from /home/tob/bin/language_server-ruby:23:in `load'
        from /home/tob/bin/language_server-ruby:23:in `<main>'
````

**Comment by ibotty** [comment]
There are also crashes when completing:

```
D, [2017-10-12T13:04:43.384196 #6211] DEBUG -- : Receive: {
  "jsonrpc": "2.0",
  "id": 1,
  "method": "textDocument/completion",
  "params": {
    "textDocument": {
      "uri": "file:///redacted"
    },
    "position": {
      "line": 8,
      "character": 5
    }
  }
}
/home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server/project.rb:70:in `find_nearest_node': undefined method `modules' for nil:NilClass (NoMethodError)
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server/project.rb:28:in `constants'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server/completion_provider/ad_hoc.rb:14:in `call'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:130:in `each'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:130:in `flat_map'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:130:in `block in <module:LanguageServer>'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:45:in `block in run'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-protocol-0.4.0/lib/language_server/protocol/transport/stdio/reader.rb:27:in `read'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/lib/language_server.rb:34:in `run'
	from /home/tob/.gem/ruby/2.4.0/gems/language_server-0.7.0/exe/language_server-ruby:8:in `<top (required)>'
	from /home/tob/bin/language_server-ruby:23:in `load'
	from /home/tob/bin/language_server-ruby:23:in `<main>'
```

Note: I am using a globally installed language_server-ruby.

**Comment by mtsmfm** [comment]
@ibotty Thank you for your reporting!
Could you tell me the file you were editing and project you were opening?

**Comment by ibotty** [comment]
Unfortunately, it's a proprietary rails project. I will try to find a simple open source project to reproduce.

**Comment by kwerle** [comment]
This is easy to reproduce - it is a startup condition.  If you rush the parser, this is what happens.  I will have a messy pull request to address this.
https://github.com/mtsmfm/language_server-ruby/issues/36
